### ISSUE TITLE
Heroku Django build log

### ISSUE THREAD

**Issue by metaljerk** [metaljerk/SoundBoard#10]
-----> Building on the Heroku-18 stack
-----> Python app detected
-----> Requirements file has been changed, clearing cached dependencies
-----> Installing python-3.6.12
-----> Installing pip 20.1.1, setuptools 47.1.1 and wheel 0.34.2
-----> Installing SQLite3
-----> Installing requirements with pip
       Collecting django
         Downloading Django-3.1.5-py3-none-any.whl (7.8 MB)
       Collecting gunicorn
         Downloading gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
       Collecting psycopg2-binary
         Downloading psycopg2_binary-2.8.6-cp36-cp36m-manylinux1_x86_64.whl (3.0 MB)
       Collecting sqlparse>=0.2.2
         Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
       Collecting pytz
         Downloading pytz-2020.5-py2.py3-none-any.whl (510 kB)
       Collecting asgiref<4,>=3.2.10
         Downloading asgiref-3.3.1-py3-none-any.whl (19 kB)
       Installing collected packages: sqlparse, pytz, asgiref, django, gunicorn, psycopg2-binary
       Successfully installed asgiref-3.3.1 django-3.1.5 gunicorn-20.0.4 psycopg2-binary-2.8.6 pytz-2020.5 sqlparse-0.4.1
-----> $ python soundboard/manage.py collectstatic --noinput
       Traceback (most recent call last):
         File "soundboard/manage.py", line 22, in <module>
           main()
         File "soundboard/manage.py", line 18, in main
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
           output = self.handle(*args, **options)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 194, in handle
           collected = self.collect()
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 118, in collect
           handler(path, prefixed_path, storage)
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 345, in copy_file
           if not self.delete_file(path, prefixed_path, source_storage):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 255, in delete_file
           if self.storage.exists(prefixed_path):
         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 311, in exists
           return os.path.exists(self.path(name))
         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 38, in path
           raise ImproperlyConfigured("You're using the staticfiles app "
       django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
 !     Error while running '$ python soundboard/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by metaljerk** [comment]
https://github.com/heroku/django-heroku

**Comment by metaljerk** [comment]
I think this will fix it: https://www.mattlayman.com/understand-django/serving-static-files/

**Comment by metaljerk** [comment]
Not gonna use heroku with diango branch
